name: Test package

on: [push, pull_request]

jobs:
  build-and-test:
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.stability }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [11.*, 12.*]
        stability: [prefer-lowest, prefer-stable]
        include: 
          - laravel: 11.*
            testbench: 9.*
          - laravel: 12.*
            testbench: 10.*

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer Dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-${{ matrix.laravel }}-${{ matrix.stability }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ matrix.php }}-${{ matrix.laravel }}-${{ matrix.stability }}-
            ${{ matrix.php }}-${{ matrix.laravel }}-
            ${{ matrix.php }}-

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nunomaduro/collision" --dev --no-interaction --no-update --ansi
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --ansi

      - name: Execute tests
        run: composer test:coverage

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          files: .coverage/clover.xml
          verbose: true
